"""Ensure schema matches models before run

Revision ID: cd9e56a363dd
Revises: 21ec9a28608b
Create Date: 2025-05-07 02:54:07.259391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd9e56a363dd'
down_revision: Union[str, None] = '21ec9a28608b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uk_3k4cplvh82srueuttfkwnylq0', 'app_user', type_='unique')
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=False)
    op.create_index(op.f('ix_app_user_id'), 'app_user', ['id'], unique=False)
    op.create_index(op.f('ix_app_user_username'), 'app_user', ['username'], unique=True)
    op.create_index(op.f('ix_communication_created_by_id'), 'communication', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_communication_id'), 'communication', ['id'], unique=False)
    op.create_index(op.f('ix_document_doc_type_id'), 'document', ['doc_type_id'], unique=False)
    op.create_index(op.f('ix_document_id'), 'document', ['id'], unique=False)
    op.create_index(op.f('ix_document_owned_by_id'), 'document', ['owned_by_id'], unique=False)
    op.create_index(op.f('ix_document_type_id'), 'document_type', ['id'], unique=False)
    op.create_index(op.f('ix_link_destination_id'), 'link', ['destination_id'], unique=False)
    op.create_index(op.f('ix_link_id'), 'link', ['id'], unique=False)
    op.create_index(op.f('ix_link_source_id'), 'link', ['source_id'], unique=False)
    op.create_index(op.f('ix_note_id'), 'note', ['id'], unique=False)
    op.create_index(op.f('ix_note_owner_id'), 'note', ['owner_id'], unique=False)
    op.create_index(op.f('ix_note_parent_id'), 'note', ['parent_id'], unique=False)
    op.create_index(op.f('ix_note_type_id'), 'note', ['type_id'], unique=False)
    op.create_index(op.f('ix_note_type_id'), 'note_type', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_type_id'), table_name='note_type')
    op.drop_index(op.f('ix_note_type_id'), table_name='note')
    op.drop_index(op.f('ix_note_parent_id'), table_name='note')
    op.drop_index(op.f('ix_note_owner_id'), table_name='note')
    op.drop_index(op.f('ix_note_id'), table_name='note')
    op.drop_index(op.f('ix_link_source_id'), table_name='link')
    op.drop_index(op.f('ix_link_id'), table_name='link')
    op.drop_index(op.f('ix_link_destination_id'), table_name='link')
    op.drop_index(op.f('ix_document_type_id'), table_name='document_type')
    op.drop_index(op.f('ix_document_owned_by_id'), table_name='document')
    op.drop_index(op.f('ix_document_id'), table_name='document')
    op.drop_index(op.f('ix_document_doc_type_id'), table_name='document')
    op.drop_index(op.f('ix_communication_id'), table_name='communication')
    op.drop_index(op.f('ix_communication_created_by_id'), table_name='communication')
    op.drop_index(op.f('ix_app_user_username'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_id'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.create_unique_constraint('uk_3k4cplvh82srueuttfkwnylq0', 'app_user', ['username'])
    # ### end Alembic commands ###
