"""Ensure schema matches models before run

Revision ID: cd9e56a363dd
Revises: 21ec9a28608b
Create Date: 2025-05-07 02:54:07.259391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd9e56a363dd'
down_revision: Union[str, None] = '21ec9a28608b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Helper function to generate index names consistently
# Replicates op.f() logic roughly for use in raw SQL
def _index_name(name: str) -> str:
    # Simplified version, assumes default naming convention used by op.f()
    # Might need adjustment if you have custom naming conventions in alembic.ini
    return f"ix_{name}"


def upgrade() -> None:
    """Upgrade schema."""
    print(f"Running upgrade for revision {revision}...")
    # ### commands auto generated by Alembic - adjusted! ###

    # Handle app_user indexes and constraint
    print("  Adjusting app_user constraints and indexes...")
    try:
        op.drop_constraint('uk_3k4cplvh82srueuttfkwnylq0', 'app_user', type_='unique')
        print("    Dropped unique constraint uk_3k4cplvh82srueuttfkwnylq0.")
    except Exception as e:
        print(f"    Could not drop unique constraint uk_3k4cplvh82srueuttfkwnylq0 (maybe doesn't exist?): {e}")

    op.execute(f"CREATE INDEX IF NOT EXISTS {_index_name('app_user_email')} ON app_user (email)")
    op.execute(f"CREATE INDEX IF NOT EXISTS {_index_name('app_user_id')} ON app_user (id)")
    op.execute(f"CREATE UNIQUE INDEX IF NOT EXISTS {_index_name('app_user_username')} ON app_user (username)")
    print("    Ensured app_user indexes exist.")

    # Handle communication indexes
    print("  Ensuring communication indexes exist...")
    op.execute(f"CREATE INDEX IF NOT EXISTS {_index_name('communication_created_by_id')} ON communication (created_by_id)")
    op.execute(f"CREATE INDEX IF NOT EXISTS {_index_name('communication_id')} ON communication (id)")

    # Handle document indexes
    print("  Ensuring document indexes exist...")
    op.execute(f"CREATE INDEX IF NOT EXISTS {_index_name('document_doc_type_id')} ON document (doc_type_id)")
    op.execute(f"CREATE INDEX IF NOT EXISTS {_index_name('document_id')} ON document (id)")
    op.execute(f"CREATE INDEX IF NOT EXISTS {_index_name('document_owned_by_id')} ON document (owned_by_id)")

    # Handle document_type indexes
    print("  Ensuring document_type indexes exist...")
    op.execute(f"CREATE INDEX IF NOT EXISTS {_index_name('document_type_id')} ON document_type (id)")

    # Handle link indexes
    print("  Ensuring link indexes exist...")
    op.execute(f"CREATE INDEX IF NOT EXISTS {_index_name('link_destination_id')} ON link (destination_id)")
    op.execute(f"CREATE INDEX IF NOT EXISTS {_index_name('link_id')} ON link (id)")
    op.execute(f"CREATE INDEX IF NOT EXISTS {_index_name('link_source_id')} ON link (source_id)")

    # Handle note indexes
    print("  Ensuring note indexes exist...")
    op.execute(f"CREATE INDEX IF NOT EXISTS {_index_name('note_id')} ON note (id)")
    op.execute(f"CREATE INDEX IF NOT EXISTS {_index_name('note_owner_id')} ON note (owner_id)")
    op.execute(f"CREATE INDEX IF NOT EXISTS {_index_name('note_parent_id')} ON note (parent_id)")
    op.execute(f"CREATE INDEX IF NOT EXISTS {_index_name('note_type_id')} ON note (type_id)") # Index on note table

    # Handle note_type indexes
    print("  Ensuring note_type indexes exist...")
    # This was the specific one failing in the log:
    op.execute(f"CREATE INDEX IF NOT EXISTS {_index_name('note_type_id')} ON note_type (id)") # Index on note_type table
    print(f"Upgrade for revision {revision} complete.")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    print(f"Running downgrade for revision {revision}...")
    # ### commands auto generated by Alembic - adjusted! ###

    # Drop note_type indexes
    print("  Dropping note_type indexes...")
    op.execute(f"DROP INDEX IF EXISTS {_index_name('note_type_id')}") # Index on note_type table

    # Drop note indexes
    print("  Dropping note indexes...")
    op.execute(f"DROP INDEX IF EXISTS {_index_name('note_type_id')}") # Index on note table
    op.execute(f"DROP INDEX IF EXISTS {_index_name('note_parent_id')}")
    op.execute(f"DROP INDEX IF EXISTS {_index_name('note_owner_id')}")
    op.execute(f"DROP INDEX IF EXISTS {_index_name('note_id')}")

    # Drop link indexes
    print("  Dropping link indexes...")
    op.execute(f"DROP INDEX IF EXISTS {_index_name('link_source_id')}")
    op.execute(f"DROP INDEX IF EXISTS {_index_name('link_id')}")
    op.execute(f"DROP INDEX IF EXISTS {_index_name('link_destination_id')}")

    # Drop document_type indexes
    print("  Dropping document_type indexes...")
    op.execute(f"DROP INDEX IF EXISTS {_index_name('document_type_id')}")

    # Drop document indexes
    print("  Dropping document indexes...")
    op.execute(f"DROP INDEX IF EXISTS {_index_name('document_owned_by_id')}")
    op.execute(f"DROP INDEX IF EXISTS {_index_name('document_id')}")
    op.execute(f"DROP INDEX IF EXISTS {_index_name('document_doc_type_id')}")

    # Drop communication indexes
    print("  Dropping communication indexes...")
    op.execute(f"DROP INDEX IF EXISTS {_index_name('communication_id')}")
    op.execute(f"DROP INDEX IF EXISTS {_index_name('communication_created_by_id')}")

    # Drop app_user indexes and restore unique constraint
    print("  Dropping app_user indexes and restoring constraint...")
    op.execute(f"DROP INDEX IF EXISTS {_index_name('app_user_username')}")
    op.execute(f"DROP INDEX IF EXISTS {_index_name('app_user_id')}")
    op.execute(f"DROP INDEX IF EXISTS {_index_name('app_user_email')}")
    try:
        # Recreate the unique constraint (use IF NOT EXISTS if your PG version supports it on constraints)
        op.create_unique_constraint('uk_3k4cplvh82srueuttfkwnylq0', 'app_user', ['username'])
        print("    Restored unique constraint uk_3k4cplvh82srueuttfkwnylq0.")
    except Exception as e:
         print(f"    Could not restore unique constraint uk_3k4cplvh82srueuttfkwnylq0 (maybe already exists?): {e}")
    print(f"Downgrade for revision {revision} complete.")

    # ### end Alembic commands ###