# app/features/llm_query/schemas.py
from pydantic import BaseModel, Field
from typing import Optional, Dict, Any

class LLMQueryRequest(BaseModel):
    system_prompt: Optional[str] = Field(
        None,
        description="The system prompt to guide the LLM's behavior."
    )
    user_prompt: str = Field(
        ...,
        description="The user's prompt or question for the LLM."
    )
    model_name: Optional[str] = Field(
        None,
        description="Optional: Specify a particular LLM model to use (overrides core default)."
    )
    max_tokens: Optional[int] = Field(
        None,
        gt=0,
        description="Optional: Maximum number of tokens to generate (overrides feature default)."
    )
    temperature: Optional[float] = Field(
        None,
        ge=0.0,
        le=2.0,
        description="Optional: Sampling temperature (0.0-2.0) (overrides feature default)."
    )
    # Add other common LLM parameters if you want to expose them
    # e.g., top_p: Optional[float] = None
    #        frequency_penalty: Optional[float] = None
    #        presence_penalty: Optional[float] = None
    additional_params: Optional[Dict[str, Any]] = Field(
        None,
        description="Optional: Dictionary for any other model-specific parameters."
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "user_prompt": "Translate the following English text to French: 'Hello, world!'",
                    "system_prompt": "You are a helpful translation assistant.",
                },
                {
                    "user_prompt": "Write a short poem about a rainy day.",
                    "max_tokens": 100,
                    "temperature": 0.8,
                },
                {
                    "user_prompt": "What is the capital of France?",
                    "model_name": "qwen-turbo", # Example of specifying a different model
                }
            ]
        }
    }

class LLMUsageInfo(BaseModel):
    prompt_tokens: Optional[int] = Field(None, description="Tokens used by the prompt.")
    completion_tokens: Optional[int] = Field(None, description="Tokens generated for the completion.")
    total_tokens: Optional[int] = Field(None, description="Total tokens used in the request.")

class LLMQueryResponse(BaseModel):
    response_text: Optional[str] = Field(
        None,
        description="The text response generated by the LLM."
    )
    model_used: Optional[str] = Field(
        None,
        description="The actual LLM model that processed the request."
    )
    usage_info: Optional[LLMUsageInfo] = Field(
        None,
        description="Information about token usage."
    )
    error_message: Optional[str] = Field(
        None,
        description="Error message if the LLM query failed."
    )