from pydantic import BaseModel, Field
from typing import Optional, Dict, Any

class LLMQueryRequest(BaseModel):
    system_prompt: Optional[str] = Field(None, description="The system prompt to guide the LLM's behavior.")
    user_prompt: str = Field(..., description="The user's prompt or question for the LLM.")
    model_name: Optional[str] = Field(None, description="Optional: Specify a model to use, overriding the service default.")
    max_tokens: Optional[int] = Field(None, gt=0, description="Optional: Maximum number of tokens to generate.")
    temperature: Optional[float] = Field(None, ge=0.0, le=2.0, description="Optional: Sampling temperature (0.0-2.0).")
    additional_params: Optional[Dict[str, Any]] = Field(None, description="Optional: Dictionary for other model-specific parameters.")

class LLMUsageInfo(BaseModel):
    prompt_tokens: Optional[int] = Field(None)
    completion_tokens: Optional[int] = Field(None)
    total_tokens: Optional[int] = Field(None)

class LLMQueryResponse(BaseModel):
    response_text: Optional[str] = Field(None, description="The text response generated by the LLM.")
    model_used: Optional[str] = Field(None, description="The actual LLM model that processed the request.")
    usage_info: Optional[LLMUsageInfo] = Field(None, description="Information about token usage.")
    error_message: Optional[str] = Field(None, description="Error message if the LLM query failed.")