# app/api/v1/endpoints/assistant.py
import logging
from fastapi import APIRouter, HTTPException, status, Depends
from sqlalchemy.orm import Session
from typing import Annotated # Optional, for cleaner dependency syntax

# Import Schemas (Ensure app.schemas.assistant exists and uses 'use_semantic_search')
from app import schemas

# Import the REAL Assistant Service (Ensure app.services.assistant_service exists and uses the new flag)
from app.services import assistant_service

# Import DB Dependency
from app.core.database import get_db

logger = logging.getLogger(__name__)
router = APIRouter()

# Define type alias for the database session dependency
DbDependency = Annotated[Session, Depends(get_db)]

@router.post(
    "/query",
    response_model=schemas.assistant.AssistantResponse, # Uses the response schema from schemas.assistant
    status_code=status.HTTP_200_OK,
    summary="Process User Query with Multiple Context Sources",
    description="""
Takes a user's query and optional flags/IDs.
Retrieves context via explicitly selected Notes, semantic search (RAG) over the knowledge base,
and/or real-time Web Search based on flags.
Uses an LLM call to synthesize an answer based on the combined context.
""",
    tags=["V1 - Assistant Query"] # Distinct tag for Swagger UI
)
async def process_assistant_query(
    request: schemas.assistant.AssistantQueryRequest, # Uses the request schema from schemas.assistant (with use_semantic_search)
    db: DbDependency # Inject database session dependency
) -> schemas.assistant.AssistantResponse:
    """
    API endpoint to handle user queries via the assistant, potentially using
    selected notes, semantic search (RAG), and web search for context.
    """
    # --- Input Validation ---
    if not request.user_query or not request.user_query.strip():
        logger.warning("Received empty user query for assistant.")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="User query cannot be empty."
        )

    # --- Log Request (using updated flag name 'use_semantic_search') ---
    logger.info(
        f"Received assistant query: '{request.user_query[:50]}...' "
        f"(Semantic Search: {request.use_semantic_search}, Web: {request.use_web_search}, " # Updated log message
        f"Selected Notes: {request.selected_note_ids})"
    )

    try:
        # --- Call the Assistant Service Layer ---
        # The core logic resides in the assistant_service module
        response = await assistant_service.process_assistant_query(
            db=db, request=request
        )
        # --- Service Layer Call End ---

        logger.info(f"Assistant processing completed for query: '{request.user_query[:50]}...'")
        # Return the response generated by the service layer
        return response

    except HTTPException as http_exc:
        # If the service layer raises an HTTPException (e.g., for specific validation), re-raise it
        logger.warning(f"HTTP Exception during assistant processing: {http_exc.status_code} - {http_exc.detail}")
        raise http_exc
    except Exception as e:
        # Catch any unexpected errors during the process
        error_message = (
            f"Unexpected error during assistant processing for query "
            f"'{request.user_query[:50]}...': {type(e).__name__} - {e}"
        )
        logger.exception(error_message) # Log the full traceback for debugging

        # Return a generic 500 Internal Server Error to the client
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An internal server error occurred while processing your query. Please try again later."
        )